# Generated by Django 5.1.6 on 2025-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemusic',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
