# Generated by Django 5.1.6 on 2025-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
